package com.epam.automation;

     enum Manufacturer{
         ACURA, ALFA_ROMEO, ASTON_MARTIN, AUDI, BENTLEY, BMW,
         BUGATTI, CADILLAC, CHEVROLET, CHRYSLER, CITROEN, DODGE,
         FERRARI, FORD, HONDA, HYUNDAI, JAGUAR, JEEP, KIA,
         LAMBORGHINI, LAND_ROVER, LEXUS, MASERATI, MAZDA, MITSUBISHI,
         NISSAN, PEUGEOT, PORSCHE, RENAULT, ROLLS_ROYCE, SUBARU,
         SUZUKI, TESLA, TOYOTA, VOLKSWAGEN
    }
